In [ ]:
'''
Ayman Ramadan Elgamal - 320220220
Yoeel Sameh Nageh  - 320220203
'''

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [72]:
data = pd.read_csv('weatherHistory.csv')

In [73]:
data.head()

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.

from matplotlib import pyplot as plt
_df_12['Temperature (C)'].plot(kind='hist', bins=20, title='Temperature (C)')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_13['Apparent Temperature (C)'].plot(kind='hist', bins=20, title='Apparent Temperature (C)')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_14['Humidity'].plot(kind='hist', bins=20, title='Humidity')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_15['Wind Speed (km/h)'].plot(kind='hist', bins=20, title='Wind Speed (km/h)')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_16.groupby('Formatted Date').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_17.groupby('Summary').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_18.plot(kind='scatter', x='Temperature (C)', y='Apparent Temperature (C)', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_19.plot(kind='scatter', x='Apparent Temperature (C)', y='Humidity', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_20.plot(kind='scatter', x='Humidity', y='Wind Speed (km/h)', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_21.plot(kind='scatter', x='Wind Speed (km/h)', y='Wind Bearing (degrees)', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['Formatted Date']
  ys = series['Temperature (C)']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_22.sort_values('Formatted Date', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('Formatted Date')):
  _plot_series(series, series_name, i)
  fig.legend(title='Formatted Date', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('Formatted Date')
_ = plt.ylabel('Temperature (C)')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['Formatted Date']
  ys = series['Temperature (C)']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_23.sort_values('Formatted Date', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('Summary')):
  _plot_series(series, series_name, i)
  fig.legend(title='Summary', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('Formatted Date')
_ = plt.ylabel('Temperature (C)')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['Formatted Date']
  ys = series['Apparent Temperature (C)']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_24.sort_values('Formatted Date', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('Formatted Date')):
  _plot_series(series, series_name, i)
  fig.legend(title='Formatted Date', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('Formatted Date')
_ = plt.ylabel('Apparent Temperature (C)')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['Formatted Date']
  ys = series['Apparent Temperature (C)']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_25.sort_values('Formatted Date', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('Summary')):
  _plot_series(series, series_name, i)
  fig.legend(title='Summary', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('Formatted Date')
_ = plt.ylabel('Apparent Temperature (C)')

from matplotlib import pyplot as plt
_df_26['Temperature (C)'].plot(kind='line', figsize=(8, 4), title='Temperature (C)')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_27['Apparent Temperature (C)'].plot(kind='line', figsize=(8, 4), title='Apparent Temperature (C)')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_28['Humidity'].plot(kind='line', figsize=(8, 4), title='Humidity')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_29['Wind Speed (km/h)'].plot(kind='line', figsize=(8, 4), title='Wind Speed (km/h)')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['Summary'].value_counts()
    for x_label, grp in _df_30.groupby('Formatted Date')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('Formatted Date')
_ = plt.ylabel('Summary')

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_31['Formatted Date'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_31, x='Temperature (C)', y='Formatted Date', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_32['Summary'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_32, x='Temperature (C)', y='Summary', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_33['Formatted Date'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_33, x='Apparent Temperature (C)', y='Formatted Date', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_34['Summary'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_34, x='Apparent Temperature (C)', y='Summary', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

In [74]:
data['Formatted Date'] = pd.to_datetime(data['Formatted Date'])

In [7]:
data.describe()

,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars)
count,96453.000000,96453.000000,96453.000000,96453.000000,96453.000000,96453.000000,96453.0,96453.000000
mean,11.932678,10.855029,0.734899,10.810640,187.509232,10.347325,0.0,1003.235956
std,9.551546,10.696847,0.195473,6.913571,107.383428,4.192123,0.0,116.969906
min,-21.822222,-27.716667,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
25%,4.688889,2.311111,0.600000,5.828200,116.000000,8.339800,0.0,1011.900000
50%,12.000000,12.000000,0.780000,9.965900,180.000000,10.046400,0.0,1016.450000
75%,18.838889,18.838889,0.890000,14.135800,290.000000,14.812000,0.0,1021.090000
max,39.905556,39.344444,1.000000,63.852600,359.000000,16.100000,0.0,1046.380000

from matplotlib import pyplot as plt
_df_0['Temperature (C)'].plot(kind='hist', bins=20, title='Temperature (C)')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1['Apparent Temperature (C)'].plot(kind='hist', bins=20, title='Apparent Temperature (C)')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_2['Humidity'].plot(kind='hist', bins=20, title='Humidity')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_3['Wind Speed (km/h)'].plot(kind='hist', bins=20, title='Wind Speed (km/h)')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_4.plot(kind='scatter', x='Temperature (C)', y='Apparent Temperature (C)', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_5.plot(kind='scatter', x='Apparent Temperature (C)', y='Humidity', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_6.plot(kind='scatter', x='Humidity', y='Wind Speed (km/h)', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_7.plot(kind='scatter', x='Wind Speed (km/h)', y='Wind Bearing (degrees)', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_8['Temperature (C)'].plot(kind='line', figsize=(8, 4), title='Temperature (C)')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_9['Apparent Temperature (C)'].plot(kind='line', figsize=(8, 4), title='Apparent Temperature (C)')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_10['Humidity'].plot(kind='line', figsize=(8, 4), title='Humidity')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_11['Wind Speed (km/h)'].plot(kind='line', figsize=(8, 4), title='Wind Speed (km/h)')
plt.gca().spines[['top', 'right']].set_visible(False)

In [8]:
data['Loud Cover'].value_counts()

Loud Cover
0.0    96453
Name: count, dtype: int64

In [9]:
data.drop('Loud Cover', axis=1, inplace=True)
data.drop('Daily Summary', axis=1, inplace=True)

In [10]:
data['Precip Type'].value_counts()

Precip Type
rain    85224
snow    10712
Name: count, dtype: int64

In [47]:
data_Cleaned = data.copy()

data_Cleaned.drop('Precip Type', axis=1, inplace=True)
data_Cleaned.drop('Apparent Temperature (C)', axis=1, inplace=True)
data_Cleaned.drop('Wind Bearing (degrees)', axis=1, inplace=True)
data_Cleaned.drop('Visibility (km)', axis=1, inplace=True)
data_Cleaned.drop('Summary', axis=1, inplace=True)

In [48]:
data_Cleaned.head()

,Formatted Date,Temperature (C),Humidity,Wind Speed (km/h),Pressure (millibars)
0,2006-04-01 00:00:00+02:00,9.472222,0.89,14.1197,1015.13
1,2006-04-01 01:00:00+02:00,9.355556,0.86,14.2646,1015.63
2,2006-04-01 02:00:00+02:00,9.377778,0.89,3.9284,1015.94
3,2006-04-01 03:00:00+02:00,8.288889,0.83,14.1036,1016.41
4,2006-04-01 04:00:00+02:00,8.755556,0.83,11.0446,1016.51

In [49]:
data_Cleaned.sort_values(by='Formatted Date', inplace=True)

In [50]:
data_Cleaned.drop('Formatted Date', axis=1, inplace=True)

In [51]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

data_Cleaned['Pressure (millibars)'] = scaler.fit_transform(data_Cleaned[['Pressure (millibars)']])
data_Cleaned['Temperature (C)'] = scaler.fit_transform(data_Cleaned[['Temperature (C)']])
data_Cleaned['Wind Speed (km/h)'] = scaler.fit_transform(data_Cleaned[['Wind Speed (km/h)']])

In [83]:
data_Cleaned.describe()

       Temperature (C)      Humidity  Wind Speed (km/h)  Pressure (millibars)
count     96453.000000  96453.000000       96453.000000          96453.000000
mean          0.546835      0.734899           0.169306              0.958768
std           0.154737      0.195473           0.108274              0.111785
min           0.000000      0.000000           0.000000              0.000000
25%           0.429484      0.600000           0.091276              0.967048
50%           0.547925      0.780000           0.156077              0.971397
75%           0.658717      0.890000           0.221382              0.975831
max           1.000000      1.000000           1.000000              1.000000

In [102]:
def create_sequences(data, seq_length=10):
    X, y = [], []
    for i in range(len(data) - seq_length):
        X.append(data[i:i+seq_length])
        y.append(data[i+seq_length, -1])
    return np.array(X), np.array(y)

In [103]:
X, Y = create_sequences(data_Cleaned.values)

In [104]:
X[0], Y[0]

(array([[0.36288363, 0.89      , 0.26802824, 0.97159732],
        [0.37233372, 0.85      , 0.2602118 , 0.97110992],
        [0.38052381, 0.82      , 0.31719617, 0.97084233],
        [0.38124381, 0.82      , 0.2269289 , 0.97054607],
        [0.37269373, 0.86      , 0.21835603, 0.96999178],
        [0.37305373, 0.85      , 0.2491175 , 0.96913167],
        [0.3895239 , 0.79      , 0.32198689, 0.96898832],
        [0.38709387, 0.81      , 0.39813414, 0.96832891],
        [0.38916389, 0.8       , 0.36283409, 0.96828112],
        [0.39780398, 0.82      , 0.35829551, 0.96837669]]),
 np.float64(0.9685009270054855))

In [105]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42, shuffle=False)

In [106]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader

X_train = torch.tensor(X_train, dtype=torch.float32)
Y_train = torch.tensor(Y_train, dtype=torch.float32)
X_test = torch.tensor(X_test, dtype=torch.float32)
Y_test = torch.tensor(Y_test, dtype=torch.float32)

batch_size = 32
train_dataset = TensorDataset(X_train, Y_train)
test_dataset = TensorDataset(X_test, Y_test)
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

In [109]:
class WeatherRNN(nn.Module):
    def __init__(self, input_size, hidden_size, num_layers):
        super(WeatherRNN, self).__init__()
        self.gru = nn.GRU(input_size, hidden_size, num_layers, batch_first=True)
        self.fc = nn.Linear(hidden_size, 1)

    def forward(self, x):
        out, _ = self.gru(x)
        out = self.fc(out[:, -1, :])
        return out

model = WeatherRNN(input_size=4, hidden_size=64, num_layers=2)

loss_fn = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

In [114]:
# Training loop
epochs = 20
for epoch in range(epochs):
    model.train()
    total_loss = 0
    for batch_X, batch_y in train_loader:
        optimizer.zero_grad()
        outputs = model(batch_X)
        loss = loss_fn(outputs, batch_y)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()

    # Evaluation
    model.eval()
    y_pred, y_true = [], []
    test_loss = 0
    with torch.no_grad():
        for batch_X, batch_y in test_loader:
            outputs = model(batch_X)
            y_pred.extend(outputs.cpu().numpy())
            y_true.extend(batch_y.cpu().numpy())
            test_loss += loss_fn(outputs, batch_y).item()

    rmse = np.sqrt(np.mean((np.array(y_pred) - np.array(y_true))**2))

    print(f'Epoch [{epoch+1}/{epochs}], Train Loss: {total_loss/len(train_loader):.4f}, Test Loss: {test_loss/len(test_loader):.4f}, RMSE: {rmse:.2f}')

Epoch [1/20], Train Loss: 0.0171, Test Loss: 0.0178, RMSE: 0.13
Epoch [2/20], Train Loss: 0.0115, Test Loss: 0.0176, RMSE: 0.13
Epoch [3/20], Train Loss: 0.0114, Test Loss: 0.0176, RMSE: 0.13
Epoch [4/20], Train Loss: 0.0113, Test Loss: 0.0176, RMSE: 0.13
Epoch [5/20], Train Loss: 0.0113, Test Loss: 0.0178, RMSE: 0.13
Epoch [6/20], Train Loss: 0.0113, Test Loss: 0.0177, RMSE: 0.13
Epoch [7/20], Train Loss: 0.0113, Test Loss: 0.0179, RMSE: 0.13
Epoch [8/20], Train Loss: 0.0113, Test Loss: 0.0176, RMSE: 0.13
Epoch [9/20], Train Loss: 0.0112, Test Loss: 0.0178, RMSE: 0.13
Epoch [10/20], Train Loss: 0.0113, Test Loss: 0.0177, RMSE: 0.13
Epoch [11/20], Train Loss: 0.0113, Test Loss: 0.0177, RMSE: 0.13
Epoch [12/20], Train Loss: 0.0113, Test Loss: 0.0178, RMSE: 0.13
Epoch [13/20], Train Loss: 0.0112, Test Loss: 0.0176, RMSE: 0.13
Epoch [14/20], Train Loss: 0.0113, Test Loss: 0.0177, RMSE: 0.13
Epoch [15/20], Train Loss: 0.0112, Test Loss: 0.0177, RMSE: 0.13
Epoch [16/20], Train Loss: 0.0112, Test Loss: 0.0178, RMSE: 0.13
Epoch [17/20], Train Loss: 0.0112, Test Loss: 0.0176, RMSE: 0.13
Epoch [18/20], Train Loss: 0.0112, Test Loss: 0.0177, RMSE: 0.13
Epoch [19/20], Train Loss: 0.0112, Test Loss: 0.0178, RMSE: 0.13
Epoch [20/20], Train Loss: 0.0112, Test Loss: 0.0176, RMSE: 0.13